### ISSUE TITLE
Prometheus4J License File

### ISSUE THREAD

**Issue by profitware** [anhdat/prometheus4j#6]
Hi @anhdat ,

Thank you for your effort on Prometheus API Client for Java development. Is it safe to assume that the code is distributed under MIT License as specified in License section of README.md? If that's Okay with you, I would like to suggest adding LICENSE.md file that explicitly states the License.

Although your code is already incorporated in a number of projects publicly available on GitHub and Maven (e.g., https://github.com/openaire/metrics-delivery-endpoint/tree/master/3rdparty-prometheus4j), it is still considered best practice to include LICENSE.md.

References:
1. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license
2. https://opensource.stackexchange.com/a/1721
3. https://github.com/organicinternet/magento-configurable-simple/issues/222#issuecomment-135201411

Adding LICENSE file can be done using GitHub inbuilt capabilities by pressing a button here: https://github.com/anhdat/prometheus4j/community/license/new?branch=master&template=mit

Thank you.

**Comment by anhdat** [comment]
Hi @profitware thanks for flagging this and the extremely useful links, I've added the license via #7
